#                                                         # 
# Configuration file for BookLecterns Minecraft Plugin    # 
# https://www.spigotmc.org/resources/book-lecterns.36689/ # 
#                                                         # 

# Should lecterns be able to look in adjacent 
# chests or solely just attached item frames?
lectern-chests: true

# Should lecterns be able to detect
# non- written book contents?
non-written-books: true

# If this is set to true, lectern creators will have to place a paper titled
# "[Display]" in their chests in order for lecterns to be able to access them.
chest-access-needed: false

# If this is set to false, lectern creators will have to place a paper titled 
# "[Display All]" in their chests in order to display non- written book contents.
all-contents-shown: false

# If only one book is supplied to the lectern, 
# should it be selected and viewed automatically?
quick-display: true
